### ISSUE TITLE
User Story: Add/Update running events

### ISSUE THREAD

**Issue by Luis-Otter** [Luis-Otter/love-running#4]
**In order to** *add events/updates* **as a** *administrator*, **I can** add upcoming running events.

## Acceptance Criteria:

1.  Form to submit new running event
2.  Form to edit a current running event

### Tasks:

- [ ] Create form for adding running events
- [ ] Create calendar to make future events viewable
- [ ] Create a form for editing current event info

**Comment by Luis-Otter** [comment]
This is completed.
